apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-enterprise.fullname" . }}-angular
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-angular
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "todo-enterprise.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-angular
